name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
            
      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test   
